//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTraderRI.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTraderRI.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cannot convert from type {0} to enum type {1}.  The source value must be a string type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotConvertFromTypeToEnum {
            get {
                return ResourceManager.GetString("CannotConvertFromTypeToEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter should be convertible to an integer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotConvertParameterToIntegerException {
            get {
                return ResourceManager.GetString("CannotConvertParameterToIntegerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Behavior cannot be attached to a null Region. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidAttachedRegion {
            get {
                return ResourceManager.GetString("InvalidAttachedRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot apply ActivateViewOnFocusBehavior to a Region that contains Views that are not UIElement. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidViewOnActivateViewOnFocusBehavior {
            get {
                return ResourceManager.GetString("InvalidViewOnActivateViewOnFocusBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The type {0} does not have a public property named &apos;{1}&apos;. The current implementation of &apos;{2}&apos; does not allow specifying a nested path or a member that is not a property. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectorExtensionCannotResolveMember {
            get {
                return ResourceManager.GetString("SelectorExtensionCannotResolveMember", resourceCulture);
            }
        }
    }
}
