//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTraderRI.Modules.Position.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTraderRI.Modules.Position.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfAccountPosition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;AccountPosition&gt;
        ///    &lt;TickerSymbol&gt;STOCK0&lt;/TickerSymbol&gt;
        ///    &lt;CostBasis&gt;280.99&lt;/CostBasis&gt;
        ///    &lt;Shares&gt;10&lt;/Shares&gt;
        ///  &lt;/AccountPosition&gt;
        ///  &lt;AccountPosition&gt;
        ///    &lt;TickerSymbol&gt;STOCK2&lt;/TickerSymbol&gt;
        ///    &lt;CostBasis&gt;1900.22&lt;/CostBasis&gt;
        ///    &lt;Shares&gt;100&lt;/Shares&gt;
        ///  &lt;/AccountPosition&gt;
        ///  &lt;AccountPosition&gt;
        ///    &lt;TickerSymbol&gt;STOCK3&lt;/TickerSymbol&gt;
        ///    &lt;Cost [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountPositions {
            get {
                return ResourceManager.GetString("AccountPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shares must be greater than 0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidSharesRange {
            get {
                return ResourceManager.GetString("InvalidSharesRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The stop limit price must be greater than 0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidStopLimitPrice {
            get {
                return ResourceManager.GetString("InvalidStopLimitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An order has been submitted.
        ///Order Details: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOrderSubmitted {
            get {
                return ResourceManager.GetString("LogOrderSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You don&apos;t have {0} shares to sell に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotEnoughSharesToSell {
            get {
                return ResourceManager.GetString("NotEnoughSharesToSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Limit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderType_Limit {
            get {
                return ResourceManager.GetString("OrderType_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Market に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderType_Market {
            get {
                return ResourceManager.GetString("OrderType_Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderType_Stop {
            get {
                return ResourceManager.GetString("OrderType_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The provided String argument {0} must not be null or empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End of day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimeInForce_EndOfDay {
            get {
                return ResourceManager.GetString("TimeInForce_EndOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thirty days に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimeInForce_ThirtyDays {
            get {
                return ResourceManager.GetString("TimeInForce_ThirtyDays", resourceCulture);
            }
        }
    }
}
